trigger:
- main

resources:
- repo: self

pool:
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean:
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectName=maven-project
          sonar.projectKey=maven-project
          sonar.qualitygate.wait=true
          sonar.qualitygate.timeout=300
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'Maven-Feed'
        mavenServiceConnections: 'Maven'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy sonar:sonar'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CmdLine@2
      inputs:
        script: |
          /opt/packer plugins install github.com/hashicorp/azure
          /opt/packer plugins install github.com/hashicorp/ansible
          chmod +x create-infra.sh
          sh create-infra.sh
