# Create a Golden AMI with Tomcat installed
---
- name: This is a playbook
  hosts: 127.0.0.1
  become: yes
  tasks:
  - name: download the java 11
    yum: 
      name: java-11*
      state: present
  - name: create directory for tomcat
    file:
      path: /opt/apache-tomcat
      state: directory
  - name: download the tomcat package from the given link
    get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz
      dest: /opt/
  - name: unarchive the tomcat file
    unarchive:
      src: /opt/apache-tomcat-8.5.100.tar.gz
      dest: /opt/
  - name: start tomcat on port 80
    replace:
      path: /opt/apache-tomcat-8.5.100/conf/server.xml
      regexp: 'port="8080"'
      replace: 'port="80"'
  - name: create tomcat as a service
    copy:
      content: |
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target
        [Service]
        Type=forking
        User=root
        Environment="CATALINA_PID=/opt/apache-tomcat-8.5.100/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/apache-tomcat-8.5.100"
        Environment="CATALINA_HOME=/opt/apache-tomcat-8.5.100"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/apache-tomcat-8.5.100/bin/startup.sh
        ExecStop=/opt/apache-tomcat-8.5.100/bin/shutdown.sh
        Restart=on-abnormal
        [Install]
        WantedBy=multi-user.target 
      dest: /etc/systemd/system/tomcat.service
  - name: reload the SystemD for configurations to be read again
    systemd:
      daemon-reload: yes
  - name: start tomcat and enable
    systemd:
      name: tomcat
      state: started
      enabled: true
  - name: To check the status of tomcat service      ### Answer for Question 3 
    shell: systemctl status tomcat
